# -*- coding: utf-8 -*-
"""Yogeshwaran_Python_lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D_-xhI6rFMGrPc5M0atZ_wyji9Tsa0Cm
"""

#Ex-1
#1(integer)
data=22
data
print(data)
type(data)

#2(Float)
data_float=13.9
print(data_float)
print(type(data_float))

#3 (string)
text='I am Inevitable'
print(text)
print(text.upper())
print(text.lower())
text.replace('Inevitable','Ironman')

#4 typecasting
mark1=78
mark2=91
mark3=87
mark4=54
mark5=66
average=(mark1+mark2+mark3+mark4+mark5)/5
print("the average value is",average)
print(type(average))
int(average)

#5 Data structures(List)
name=['Yogesh','Waran','sri','durga','goodson']
gender=['m','f','f','f','m']
age=[20,21,20,22,24]
register_no=[881,882,883,884,885]
nationality=['T','T','F','T','F']
list=[name,gender,age,register_no,nationality]
print(list)
print(len(name))
age.append(23)
print(age)
gender.extend(['m','f'])
print(gender)
del(register_no[3])
print(register_no)
detail=name+gender+age
print(detail)
a='male'
if a in gender:
  print('exist')
else:
  print('not exist')



#6 Data Structures (Tuples):
my_data=(4500,'Yogesh','Waran',4.8,4.8)
print(my_data)
print(my_data[1])
print(my_data[1:3])
a=my_data.count(4.8)
print(a)
b=my_data.index('Suresh')
print(b)

#7 Data structures(Dictionary)
wt_corpa={'hlo':'hello','gud':'good','ni8':'night','bi':'bye','tc':'take care',}
print(wt_corpa)
print(wt_corpa.keys())
print(wt_corpa['hlo'])
del(wt_corpa['hlo'])
wt_corpa['university']='bu'
print(wt_corpa)

#EX2:Conditional Statements and Looping 
#1 Electricity Bill
def house():
  unit=int(input("enter your unit:"))
  if(unit <= 100):
    bill = unit*0.05
  elif unit >= 101 and unit <= 200:
    bill = 5+((unit-100)*0.75)
  elif unit >= 201 and unit <= 300:
    bill=5+75+((unit-200)*1.20)
  else:
    bill = 5+75+120+((unit - 300)*1.50)
  print("Bill per unit:",bill)
def commercial():
  unit=int(input("enter your unit:"))
  if(unit<=100):
    bill = unit*0.05*2
  elif unit>=101 and unit <=200:
    bill = 5+((unit-100))*0.75*2
  elif unit >= 201 and unit<= 300:
    bill= 5 +75+120+((unit-300)*1.50*2)
  print("Bill per unit:",bill)
ch=0
while ch==0:
  ch=int(input("enter the choice 1 for house 2 for commercial:"))
  if ch==1:
    house();
  elif ch==2:
    commercial();
  else:
    print("invalid choice")

#Ex. 3: OOPS Concepts: Functions & Inheritance  
#1 Quiz Using Functions: 
class Question:
     def __init__(self, prompt, answer):
          self.prompt = prompt
          self.answer = answer
question_prompts = [
    "Hacking is illegal? \n a)True\n b)False \n\n",
    "nmap is used for port scan? \n a)True\n b)False \n\n",
    "Kali is os? \n a)True\n b)False \n\n",
    "Python is used for hacking? \n a)True\n b)False \n\n",
    "Dos attack can dowm the server? \n a)True\n b)False \n\n",
    ]
questions = [
     Question(question_prompts[0], "b"),
     Question(question_prompts[1], "a"),
     Question(question_prompts[1], "a"),
     Question(question_prompts[1], "a"),
     Question(question_prompts[1], "a"),
]
def run_quiz(questions):
     score = 0
     for question in questions:
          answer = input(question.prompt)
          if answer == question.answer:
               score += 1
     print("score:", score)
run_quiz(questions)

#task2(calculate net salary and gross salary)
class Employee:
  def getEmployee(my):
    my.salary = int(input("Enter Empolyees Basic Salary:"))
    return(my.salary)
class Perks(Employee):
  def calcPerks(my):
    bs=my.getEmployee()
    my.da=bs*0.20
    my.hra=bs*0.1
    my.ta=bs*0.075
    my.emi=bs*0.02
    my.pf=bs*0.12
    my.gs=bs+my.da+my.hra+my.ta
    my.ns=my.gs-my.pf-my.emi
    print('Net Salary:',my.ns)
    print("Gross Salary:",my.gs)
empsalary = Perks()
empsalary.calcPerks()

#Ex4 Data Manipulation Using Pandas
import pandas as pd
#1 Create a dataframe
df = pd.DataFrame({
'Roll No':[1,2,3,4,5],
'Name':['Yogeshwaran','Thiru','Santhosh','Neveas','Elavarasu'],
'Fathers_Name':['Yogesh','Arulnathan','Sandy','Pondi','Arasu'],
'DOB':[2001,1974,1999,1974,1980],
'Status':['Son','Son','Son','Son','Son']
})
df['age']=2022-df['DOB']
df['Father_age']=2*df['age']
df['Father_status']=df['Father_age'].apply(lambda x: 'retired' if x>58 else 'not retired')
df['gender']=df['Status'].apply(lambda x: 'M' if x =='Son' else 'F')
display(df)

#2 Select columns with specific data types
columns = df.select_dtypes(include=['int'])
print(columns,'\n')

#3 Slicing the dataframe
print(df.loc[0:5,'Fathers_Name':'DOB'],'\n')

#4 Select specific values in the column
print(df.iloc[1:2, 1:2],'\n')

#5 Group by Age
print(df.groupby(['age','Status']).groups)

#6 Map with dataframe 
df['MARRIED']=df['age'].map(lambda x: 'YES' if x>24 else 'NO')
print(df['MARRIED'])

#7 Rename the column name
df.rename(columns = {'MARRIED':'MARRIED_STATUS'}, inplace = True)
display(df)

#8 Drop columns & rows in the dataframe
df.drop(df.index[1:3], inplace=True)
df.drop(['Roll No'], axis=1,inplace=True)
print(df)
display(df)

#9 Write/Read as CSV file
df.to_csv("df.csv")
df=pd.read_csv("/content/df.csv")
df

!pip install pygooglenews

#Ex6. Modular Programming: Scrap news from Hacker News
from google.colab import files
uploaded = files.upload()

import news as n
df1=n.scrap_news("hacker news")
display(df1)

import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS
wordcloud = WordCloud(background_color="grey",width=1600, height=800).generate(''.join(df1['title'].tolist()))
plt.figure( figsize=(12,10), facecolor='k')
plt.imshow(wordcloud)

!pip install scapy

#Ex7.Banner Grabbing Scapy
import socket
import requests
from scapy.all import sniff
#getting ip of domain
hostname = input("Enter the website url (full)")
ip= socket.gethostbyname(hostname)
print(hostname,"\n",ip)
#Banner grabbing
def banner(ip, port):
    s = socket.socket()
    s.connect((ip, int(port)))
    print(s.recv(1024))
port = str(input("Please enter the port: "))
banner(ip, port)
print(hostname)
#check if vulnerable
domain = "https://www."+hostname
headers= requests.get(domain).headers

if 'X-Frame-Options' in headers:
    print(domain," non - vulnerable")
else:
    print(domain, " vulnerable")

!pip install pynput

#Ex 8 Design a Keylogger
from pynput.keyboard import Key, Listener
def on_press(key):
    print('{0} pressed'.format(key))
def on_release(key):
    if key == Key.esc:
        return False
# Collect events until released
with Listener(on_press=on_press,on_release=on_release) as listener:
  listener.join()